config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    resources :issues do
      resources :entries
    end
  end

  root "welcome#index"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :issue

  mount_uploader :picture, PictureUploader

  validates :posted_by, presence: true
  validates :body, presence: true
  validate :picture_size

  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :user
  has_many :entries, dependent: :destroy

  validates :subject, presence: true
  validates :priority, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :issues, dependent: :destroy

  validates :first_name, presence: true, length: { minimum: 2 }, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  validates :last_name, presence: true, length: { minimum: 2 }, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  validates :company, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  layout :layout

  private

    def layout
      if is_a?(Devise::SessionsController)
        "splash"
      else
        nil
      end
    end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :company, :password, :phone_number, :password_confirmation) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :company, :phone_number, :password, :password_confirmation) }
    end

    def check_user_id
      if current_user == nil || current_user.id != params[:user_id].to_i
        redirect_to root_path
      end
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @issue = Issue.find(params[:issue_id])
    @entries = Entry.where(issue_id: @issue)
  end

  def new
    @entry = Entry.new
  end

  def create
    @issue = Issue.find(params[:issue_id])
    @entry = @issue.entries.create(entry_params)
    if @entry.valid?
      flash[:success] = "Entry posted!"
      redirect_to user_issue_entries_path(current_user, @issue)
    else
      flash[:error] = {title: "Invalid Entry!", messages: @entry.errors.full_messages}
      redirect_to new_user_issue_entry_path(current_user, @issue)
    end
  end

  private

    def entry_params
      params.require(:entry).permit(:posted_by, :body, :picture)
    end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = Issue.where(user_id: current_user).order('created_at desc')
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.create(issue_params)
    if @issue.valid?
      current_user.issues << @issue
      flash[:success] = "Issue Created!"
      redirect_to user_issue_path(current_user, @issue)
    else
      #TODO display full messages to user
      flash[:alert] = "Error: Could not create this issue!"
      render 'new'
    end
  end

  def show
    @issue = Issue.find(params[:id])
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def update
    @issue = Issue.find(params[:id])
    @issue.update(issue_params)
    if @issue.valid?
      flash[:success] = "Issue Updated!"
      redirect_to user_issue_path(current_user, @issue)
    else
      flash[:error] = "Error, could not update!"
    end
  end

  private

    def issue_params
      params.require(:issue).permit(:subject, :priority, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to user_issues_path(current_user)
    else
      redirect_to new_user_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/index.html.erb
<%= render 'shared/header', page_title: "Issue ##{@issue.id} History" %>
<div class="container">
  <%= link_to "< Back", :back %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= link_to "+ Add Entry", new_user_issue_entry_path(current_user, @issue), class: "btn btn-lg form-control btn-fresh" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <% @entries.each do |entry| %>
        <div class="well entry">
          Posted by: <%= entry.posted_by %>
          <div class="pull-right">
            <%= entry.created_at.to_s(:short) %>
          </div>
          <h4><%= entry.body %></h4>
          <div>
            <%= image_tag(entry.picture.url, class: "picture") if entry.picture? %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/entries/new.html.erb
<%= render 'shared/header', page_title: "New Entry" %>
<div class="container">
  <%= link_to "< Back", :back %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@entry, url: {action: "create"}, html: {mulitpart: true, class: "form-group"}) do |f| %>
        <%= f.text_field :posted_by, placeholder: "*Posted by", class: "form-control form-fresh" %>
        <%= f.text_area :body, placeholder: "*Entry text", class: "form-control textarea-fresh" %>
        <span class="picture">
          <%= f.file_field :picture, accept: 'image/jpeg,image/jpg,image/gif,image/png' %>
        </span>
        <%= f.submit "Submit", class: "btn btn-lg btn-fresh form-control" %>
      <% end %>
    </div>
  </div>
</div>

app/views/issues/_table.html.erb
<div class="row">
  <div class="col-lg-12">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>DATE</th>
          <th>PRIORITY</th>
          <th>SUBJECT</th>
          <th>DESCRIPTION</th>
          <th>STATUS</th>
        </tr>
      </thead>
      <tbody class="table-body">
        <% issues.each do |issue| %>
          <tr data-link="<%= user_issue_path(current_user, issue)%>">
            <td data-label="ID">
              <%= issue.id %>
            </td>
            <td data-label="DATE">
              <%= issue.created_at.to_s(:long) %>
            </td>
            <td data-label="PRIORITY">
              <%= issue.priority %>
            </td>
            <td data-label="SUBJECT">
              <%= issue.subject %>
            </td>
            <td data-label="DESCRIPTION">
              <%= issue.description %>
            </td>
            <td data-label="STATUS">
              <%= issue.status %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- end column -->
</div> <!-- end row -->

app/views/issues/edit.html.erb
<%= render 'shared/header', page_title: "Edit Issue ##{@issue.id}" %>
<div class="container">
  <%= link_to "< Back", :back %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <% case @issue.status.downcase %>
      <% when "active" %>
        <div class="alert alert-success form-control form-fresh text-center">
          <p>Active</p>
        </div>
      <% when "closed" %>
        <div class="alert alert-danger form-control form-fresh text-center">
          <p>Closed</p>
        </div>
      <% end %>
      <%= form_for [current_user, @issue], url: {action: "update"}, html: {method: "patch"} do |f| %>
        <%= f.text_field :subject, placeholder: "Subject", class: "form-control form-fresh" %>
        <%= f.text_field :priority, placeholder: "Priority", class: "form-control form-fresh" %>
        <%= f.text_area :description, placeholder: "Description", class: "form-control textarea-fresh" %>
        <%= f.submit "Update Issue", class: "btn-fresh form-control" %>
      <% end %>
    </div>
  </div>
</div>

app/views/issues/index.html.erb
<%= render 'shared/header', page_title: "Dashboard" %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= link_to "My Profile", edit_user_registration_path, class: "btn btn-lg form-control btn-fresh" %>
      <%= link_to "+ Create New Issue", new_user_issue_path(current_user), class: "btn btn-lg form-control btn-fresh"  %>
      <div class="btn btn-lg form-control btn-fresh" id="view-issues-btn">
        <p>Show All Issues</p>
      </div>
    </div>
  </div>
  <br><br> <!-- take line breaks out!!! -->
  <div id="issues-table">
    <%= render 'table', issues: @issues %>
  </div>
</div> <!-- end container -->

app/views/issues/new.html.erb
<%= render 'shared/header', page_title: "Create New Issue" %>
<div class="container">
  <%= link_to "< Back", :back %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= form_for @issue, url: {action: "create"}, html: {class: "form-group"} do |f| %>
        <%= f.text_field :subject, placeholder: "* Subject", class: "form-control form-fresh" %>
        <%= f.text_field :priority, placeholder: "* Priority", class: "form-control form-fresh" %>
        <%= f.text_area :description, placeholder: "* Description of the isssue", class: "form-control textarea-fresh" %>
        <%= f.submit "Submit Issue", class: "btn btn-lg btn-fresh form-control" %>
      <% end %>
    </div>
  </div>
</div>

app/views/issues/show.html.erb
<%= render 'shared/header', page_title: "Issue ##{@issue.id}" %>
<div class="container">
  <%= link_to "< Back", :back %>
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <% case @issue.status.downcase %>
      <% when "active" %>
        <div class="alert alert-success form-control form-fresh text-center">
          <p>Active</p>
        </div>
      <% when "closed" %>
        <div class="alert alert-danger form-control form-fresh text-center">
          <p>Closed</p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row issue-info">
    <div class="col-lg-8 col-lg-offset-2">
      <h4><strong>SUBJECT:</strong> <%= @issue.subject %></h4>
      <h4><strong>DATE:</strong> <%= @issue.created_at.to_s(:long) %></h4>
      <h4><strong>ISSUE ID:</strong> <%= @issue.id %></h4>
      <h4><strong>PRIORITY:</strong> <%= @issue.priority %></h4>
      <h4><strong>DESCRIPTION:</strong> <%= @issue.description %></h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= link_to "History", user_issue_entries_path(current_user, @issue), class: "btn btn-lg form-control btn-fresh" %>
      <%= link_to "Edit This Issue", edit_user_issue_path(current_user, @issue), class: "btn btn-lg form-control btn-fresh" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="page-wrapper">
      <div id="page-header">
        <%= render 'shared/navigation' %>
      </div>

      <div id="page-content">
        <%= render 'shared/swal' %>
        <%# if notice %>
          <!-- <div class="notice alert alert-info text-center"><%= notice %></div> -->
          <!-- <div class="alert alert-succes text-center"><%= alert %></div> -->
        <%# end %>
        <%= yield %>
      </div>

      <div id="page-footer">
        <%= render 'shared/footer' %>
      </div>

    </div>
  </body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="page-wrapper">
      <div id="page-header">
        <%= render 'shared/navigation' %>
        <%= render 'shared/splash_header' %>
      </div>

      <div id="page-content">
        <%= render 'shared/swal' %>
        <%# if notice %>
          <!-- <div class="notice alert alert-info text-center"><%= notice %></div> -->
          <!-- <div class="alert alert-succes text-center"><%= alert %></div> -->
        <%# end %>
        <%= yield %>
      </div>

      <div id="page-footer">
        <%= render 'shared/footer' %>
      </div>

    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <ul>
        <li class="pull-left">
          &copy; 2015 Service Trackr
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_head.html.erb
<title>Service Trackr</title>
<link href='http://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
<%= favicon_link_tag 'favicon.ico' %>

app/views/shared/_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1 col-sm-12">
        <div class="intro-text text-center">
          <h1><%= page_title %></h1>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag 'favicon.ico', class: "navbar-brand" %>
      <%= link_to "Service Trackr", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <% if !user_signed_in? %>
          <li>
            <%= link_to "Sign up", new_user_registration_path %>
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li>
            <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </div><!-- end container-fluid -->
</nav><!-- end navbar -->

app/views/shared/_splash_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1 col-sm-12">
        <div class="intro-text text-center">
          <h1 id="title"><%= image_tag "favicon.png", class: "logo" %>Service Trackr</h1>
          <h2>The easy way to create, update, and track customer service issues.</h2>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_swal.html.erb
<% if flash[:alert] %>
  <script>
    swal({ title: <%= flash[:alert].to_json.html_safe %>,
           allowOutsideClick: true,
           type: "error"
    });
  </script>

<% elsif flash[:success] %>
  <script>
    swal({ title: <%= flash[:success].to_json.html_safe %>,
           allowOutsideClick: true,
           type: "success"
    });
  </script>

<% elsif flash.now[:error] %>
  <% content_for :error_message do %>
    <div>
      <% flash[:error]['messages'].each do |message| %>
        <div class="error-msgs"><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <script>
    swal({ title: <%= flash[:error]['title'].to_json.html_safe %>,
           text: <%= yield(:error_message).to_json.html_safe %>,
           type: 'error',
           html: true,
           allowOutsideClick: true,
    });
  </script>

<% end %>